[package]
name = "mandelbrot_generator"
version = "1.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
image = "0.25.4"
indicatif = "0.17.8"
num-complex = "0.4.6"
